[theme]
primaryColor = "#3b82f6"
backgroundColor = "#212121"
secondaryBackgroundColor = "#2f2f2f"
textColor = "#e5e5e5"
font = "sans serif"

[server]
headless = true
maxUploadSize = 50
enableCORS = false
